configfile: "config_files/arabidopsis.yaml"
use-conda: "True"
conda-frontend: "mamba"
conda-prefix: "~/.conda/envs"
resources:
  - downloads=4
printshellcmds: "True"
rerun-incomplete: "True"
rerun-triggers: "mtime" # this will prevent changes in the code from causing reruns

# Example resource configuration
# default-resources:
#   - runtime=100
#   - mem_mb=6000
#   - disk_mb=1000000
# # set-threads: map rule names to threads
# set-threads:
#   - single_core_rule=1
#   - multi_core_rule=10
# # set-resources: map rule names to resources in general
# set-resources:
#   - high_memory_rule:mem_mb=12000
#   - long_running_rule:runtime=1200
